/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Registry Tool
 #	author : miyako
 #	11/01/25
 #
 # --------------------------------------------------------------------------------*/



// --- Windows
void RT_Set_binary_value( PA_PluginParameters params );
void RT_Set_long_value( PA_PluginParameters params );
void RT_Set_expand_string_value( PA_PluginParameters params );
void RT_Set_string_value( PA_PluginParameters params );
void RT_Get_string_value( PA_PluginParameters params );
void RT_Get_long_value( PA_PluginParameters params );
void RT_Get_binary_value( PA_PluginParameters params );
void RT_Get_expand_string_value( PA_PluginParameters params );
